language: c

env:
    - SOURCE_SDK=hl2sdk-ob-valve;ENGINE=orangeboxvalve

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib

before_script:
    - mkdir sm
    - cd sm
    - hg clone http://hg.alliedmods.net/sourcemod-central 
    - hg clone http://hg.alliedmods.net/hl2sdks/$SOURCE_SDK
    - hg clone http://hg.alliedmods.net/mmsource-central/
    - cd sourcemod-central/core/
    - cp ../public/amtl/*.h ../public/
    - make ENGINE=$ENGINE
    - ls
    - ls Release.$ENGINE
    - cp test-plugin.sp addons/sourcemod/scripting/
    - ls addons/sourcemod/scripting
    - chmod +x addons/sourcemod/scripting/spcomp
    - ls ./addons/sourcemod/scripting/

script: 
    - ./addons/sourcemod/scripting/spcomp ./addons/sourcemod/scripting/test-plugin

after_script:
    - ls addons/sourcemod/scripting
