language: c

env:
    - SOURCE_SDK=hl2sdk-ob-valve;ENGINE=orangeboxvalve

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib

before_script:
    - wget http://newyork.download.maverickservers.com/source/sourcemod-1.5.0-linux.tar.gz
    - tar zxvf sourcemod-1.5.0-linux.tar.gz
    - ls
    - cp test-plugin.sp addons/sourcemod/scripting/
    - ls addons/sourcemod/scripting
    - chmod +x addons/sourcemod/scripting/spcomp
    - ls ./
    - ls ./addons/sourcemod/scripting/

script: 
    - ./addons/sourcemod/scripting/spcomp ./addons/sourcemod/scripting/test-plugin

after_script:
    - ls addons/sourcemod/scripting
