language: c

before_script:
  - wget http://newyork.download.maverickservers.com/source/sourcemod-1.5.0-linux.tar.gz
  - tar zxvf sourcemod-1.5.0-linux.tar.gz
  - ls
  - cp test-plugin.sp addons/sourcemod/scripting/
  - ls addons/sourcemod/scripting
  - ls ./

script: "./addons/sourcemod/scripting/spcomp test-plugin.sp"

after_script:
  - ls addons/sourcemod/scripting