language: c

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib

before_script:
    - wget -O smdrop15.html http://www.sourcemod.net/smdrop/1.5/
    - FILE=`egrep '"sourcemod-1\.5\..*-hg.*-linux\.tar\.gz"' smdrop15.html | cut -d '"' -f 2 | tail -1`
    - wget http://www.sourcemod.net/smdrop/1.5/$FILE
    - tar -xzf $FILE
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh
    - cp test-plugin.sp addons/sourcemod/scripting/

script: 
    - ./compile.sh

after_script:
    - ls ../plugin
