language: c

before_script:
  - wget http://newyork.download.maverickservers.com/source/sourcemod-1.5.0-linux.tar.gz
  - tar zxvf sourcemod-1.5.0-linux.tar.gz
  - ls
  - cp addons/sourcemod/scripting/spcomp .
  - ls

script: "./spcomp test-plugin.sp"