before_script:
  - ls ~/
  - wget http://newyork.download.maverickservers.com/source/sourcemod-1.5.0-linux.tar.gz
  - tar zxvf sourcemod-1.5.0-linux.tar.gz
  - ls
  - cd addons/sourcemod/scripting/
  - ls

script: "~/Alvinlz/Sourcemod-Travis/addons/sourcemod/scripting/spcomp test-plugin.sp"