language: c

before_script:
  - wget http://newyork.download.maverickservers.com/source/sourcemod-1.5.0-linux.tar.gz
  - tar zxvf sourcemod-1.5.0-linux.tar.gz
  - ls
  - cd addons/sourcemod/scripting/
  - ls

script: bash compile.sh test-plugin.sp